const ZONES=[['雲階市集','交易會改變光的去向','#315b83'],['鏡潮渡口','每一次抵達都像重逢','#396a88'],['根井庭園','根系記得每一個承諾','#506f57']];
const TYPE_ICON={角色:'♙',行動:'↯',事件:'☄',裝備:'◒',場域:'⌂',命運:'☽'};
const app=document.querySelector('#app'), root=document.querySelector('#modal-root');
let S={};
const clone=c=>({...c,uid:crypto.randomUUID()});
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const side=s=>s==='p'?'你':'電腦';
const opponent=s=>s==='p'?'b':'p';
const factionCards=f=>CARDS.filter(c=>c.f===f);
function makeDeck(f){const own=factionCards(f), fate=factionCards('fate');return shuffle([...own,...own,...fate,...fate].slice(0,30)).map(clone)}
function player(f){let deck=makeDeck(f);return {f,deck,hand:deck.splice(0,5),discard:[],res:3,fame:0,action:false,event:false,shield:0}}
function newGame(f='amber'){const fs=['amber','ember','indigo','moss'],bot=fs[(fs.indexOf(f)+1)%fs.length];S={turn:'p',round:1,timeline:0,ended:false,selected:null,tax:false,taxFor:null,counter:false,counterEvent:false,supported:{p:false,b:false},eclipse:null,p:player(f),b:player(bot),zones:ZONES.map(([n,l,t])=>({n,l,t,p:[],b:[],field:null,chair:false})),log:[]};note('曙痕再度開啟。你的回合開始。');render()}
function note(m){S.log.unshift(m)}
function draw(s,n=1){for(let i=0;i<n;i++){let x=S[s].deck.pop();if(x)S[s].hand.push(x);else if(S[s].discard.length){S[s].deck=shuffle(S[s].discard.splice(0));draw(s,1)}}}
function art(c){return FACTIONS[c.f].art}
function cardHTML(c,i,interactive=false,small=false){const f=FACTIONS[c.f],disabled=interactive&&!canUse(c);return `<button class="card ${S.selected?.i===i?'selected':''}" ${disabled?'disabled':''} ${small?'small-card':''} data-card="${interactive?i:''}" style="--accent:${f.color}2e;--art:url('${art(c)}')"><div class="card-head"><span>${c.n}</span><span class="cost">${c.c}</span></div><div class="art"><span>${TYPE_ICON[c.t]}</span></div><div class="type" style="color:${f.color}">${c.t} · ${f.name} · ${c.r}</div><div class="effect">${c.e}</div>${c.t==='角色'?`<div class="stats">⚔ <b>${c.a}</b>　◆ <b>${c.d}</b></div>`:''}<span class="info" role="button" tabindex="0" data-info="${c.id}" title="卡牌介紹">i</span></button>`}
function power(u,z,s){let n=u.card.a+u.a+(u.temp||0);if(z.field?.owner===s&&z.field.card.fx==='ashField')n+=1;if(S.eclipse===s)n+=2;return Math.max(0,n)}
function defense(u,z,s){let n=u.card.d+u.d;if(z.field?.card.fx==='greenhouse'&&z.field.owner===s)n+=1;return Math.max(1,n)}
function control(z){let p=z.p.reduce((n,u)=>n+power(u,z,'p'),0),b=z.b.reduce((n,u)=>n+power(u,z,'b'),0);if(z.field?.owner==='p'&&['archiveField','theater'].includes(z.field.card.fx))p+=1;if(z.field?.owner==='b'&&['archiveField','theater'].includes(z.field.card.fx))b+=1;if(z.field?.card.fx==='rest'){let diversity=new Set([...z.p,...z.b].map(u=>u.card.f)).size-1;if(z.field.owner==='p')p+=Math.min(3,Math.max(0,diversity));if(z.field.owner==='b')b+=Math.min(3,Math.max(0,diversity))}return {p,b,owner:p===b?null:p>b?'p':'b'}}
function unitHTML(u,z,s,i){const sel=S.selected?.mode==='attack'&&S.selected.z===z&&S.selected.i===i&&S.selected.s===s;return `<button class="unit ${u.used?'used':''} ${u.sealed?'sealed':''} ${sel?'selected':''}" data-unit="${s},${z},${i}"><b>${TYPE_ICON.角色} ${u.card.n}</b><small>⚔ ${power(u,S.zones[z],s)}　◆ ${defense(u,S.zones[z],s)}</small><em>${u.damage?`傷 ${u.damage}`:''}${u.sealed?' 封':''}</em></button>`}
function zoneHTML(z,i){let c=control(z),label=c.owner===null?'無人控制':c.owner==='p'?'你控制':'電腦控制';return `<article class="zone" style="--tint:${z.t}99"><header class="zone-head" data-zone="${i}"><div><h2>${z.n}</h2><p>${z.l}</p></div><span class="control">${label} · ${c.p}:${c.b}</span></header><div class="row"><div class="label">電腦 · ${FACTIONS[S.b.f].name}</div><div class="units">${z.b.length?z.b.map((u,x)=>unitHTML(u,i,'b',x)).join(''):'<div class="empty">尚無角色</div>'}</div></div><div class="row" data-zone="${i}"><div class="label">你 · ${FACTIONS[S.p.f].name}</div><div class="units">${z.p.length?z.p.map((u,x)=>unitHTML(u,i,'p',x)).join(''):'<div class="empty">點選角色卡部署至此</div>'}</div></div>${z.field?`<div class="field">${FACTIONS[z.field.card.f].icon} ${side(z.field.owner)}的場域：${z.field.card.n}</div>`:''}</article>`}
function prompt(){if(S.ended)return '<strong>本局結束。</strong>可重新開局或到圖鑑認識所有卡牌。';if(S.turn==='b')return '對手正在規劃回合…';if(S.selected?.mode==='zone')return `已選擇「${S.selected.card.n}」：點選一座領域。`;if(S.selected?.mode==='own')return `已選擇「${S.selected.card.n}」：點選一名己方角色。`;if(S.selected?.mode==='attack')return '已選擇交鋒角色：點選同一領域的一名對手角色。';return '先打出角色爭奪三處領域；選擇自己的角色後，點選同處對手即可交鋒。'}
function render(){if(!S.p)return;const pf=FACTIONS[S.p.f],bf=FACTIONS[S.b.f];app.innerHTML=`<main class="app"><header class="topbar"><div class="brand"><div class="sigil">✦</div><div><h1>曙痕議約</h1><p>DAWNSCAR CONCORD · 完整資料牌庫版</p></div></div><div class="controls"><button class="btn" data-action="guide">教學</button><button class="btn" data-action="collection">卡牌圖鑑</button><button class="btn gold" data-action="new">重新開局</button></div></header><section class="hud"><div class="hero" style="--f:${pf.color}"><div class="badge">${pf.icon}</div><div><div class="name">你 · ${pf.name}</div><div class="meters"><span>✦ <b>${S.p.res}</b> 曦質</span><span>✧ <b>${S.p.fame}</b>/12 聲望</span><span>牌 ${S.p.deck.length}</span></div></div></div><div class="center"><div class="round">第 ${S.round} 輪 · 終章 ${S.timeline}/10</div><div>${S.turn==='p'?'你的策議階段':'對手的策議階段'}</div></div><div class="hero right" style="--f:${bf.color}"><div><div class="name">${bf.name} · 電腦</div><div class="meters"><span>✦ <b>${S.b.res}</b></span><span>✧ <b>${S.b.fame}</b>/12</span><span>牌 ${S.b.deck.length}</span></div></div><div class="badge">${bf.icon}</div></div></section><p class="tip">${prompt()}</p><section class="layout"><div class="zones-wrap"><div class="zones">${S.zones.map(zoneHTML).join('')}</div></div><aside class="log-panel"><h2>議約紀錄</h2><div class="log" aria-live="polite">${S.log.map(x=>`<div>${x}</div>`).join('')}</div></aside></section><section class="hand-drawer"><div class="hand-top"><h2>你的手牌 · ${S.p.hand.length}</h2><div class="hand-tools"><span class="hand-hint">左右滑動查看</span><button class="btn" data-action="hand">放大檢視</button><button class="btn gold" data-action="end" ${S.turn!=='p'||S.ended?'disabled':''}>結束回合 →</button></div></div><div class="hand" aria-label="完整手牌，可左右滑動">${S.p.hand.map((c,i)=>cardHTML(c,i,true)).join('')||'<p>手牌已空。</p>'}</div></section></main>`}
function cost(c,s){return c.c+(S.tax&&S.taxFor===s&&c.t==='行動'?1:0)}
function canUse(c){return S.turn==='p'&&!S.ended&&cost(c,'p')<=S.p.res&&!(c.t==='行動'&&S.p.action)&&!(c.t==='事件'&&S.p.event)}
function takeCard(s,i){return S[s].hand.splice(i,1)[0]}
function discard(s,c){S[s].discard.push(c)}
function chooseCard(i){let c=S.p.hand[i];if(!canUse(c))return;if(c.t==='角色')S.selected={mode:'zone',card:c,i};else if(c.t==='場域')S.selected={mode:'zone',card:c,i};else if(c.t==='裝備'||['gamble','ready','ticket','medic','sacrifice','symbiosis','compass'].includes(c.fx))S.selected={mode:'own',card:c,i};else if(['archive','ironRain','scatter','chair'].includes(c.fx))S.selected={mode:'zone',card:c,i};else resolve('p',c,i);render()}
function pay(s,c){S[s].res-=cost(c,s);if(S.tax&&S.taxFor===s)S.tax=false;if(c.t==='行動')S[s].action=true;if(c.t==='事件'){S[s].event=true;S.timeline++}}
function playZone(s,c,i,z){if(c.t==='角色'){if(S.zones[z][s].length>=2){note('該領域已無己方空位。');return}pay(s,c);let u={card:c,a:0,d:0,damage:0,used:!['rush','chief'].includes(c.fx),sealed:false};S.zones[z][s].push(u);takeCard(s,i);note(`${side(s)}在<strong>${S.zones[z].n}</strong>部署「${c.n}」。`);enter(s,u,z);return}if(c.t==='場域'){pay(s,c);S.zones[z].field={owner:s,card:c};takeCard(s,i);note(`${side(s)}建立場域「${c.n}」。`);return}pay(s,c);takeCard(s,i);resolveFx(s,c,z);discard(s,c)}
function playOwn(s,c,i,z,ui){let u=S.zones[z][s][ui];if(!u)return;pay(s,c);takeCard(s,i);if(c.t==='裝備'){if(c.fx==='def2')u.d+=2;if(c.fx==='both1'||c.fx==='prism')u.a+=1,u.d+=1;if(c.fx==='compass'){u.a+=1;u.d+=1;let to=[0,1,2].find(x=>x!==z&&S.zones[x][s].length<2);if(to!==undefined)moveUnit(s,z,u,to)}if(c.fx==='atk1')u.a+=1;if(c.fx==='spear')u.a+=2,u.d-=1;if(c.fx==='ink'||c.fx==='symbiosis')u.d+=1;if(c.fx==='symbiosis')heal(u,1);note(`${side(s)}讓「${u.card.n}」裝備「${c.n}」。`)}else resolveFx(s,c,{z,ui,u});discard(s,c)}
function resolve(s,c,i){pay(s,c);takeCard(s,i);resolveFx(s,c);discard(s,c);render()}
function enter(s,u,z){const f=u.card.fx,enemy=S.zones[z][opponent(s)];if(S.zones[z].field?.owner===s&&S.zones[z].field.card.fx==='ropeField')u.used=false;if(f==='gain1')S[s].res=Math.min(5,S[s].res+1);if(f==='draw1'||f==='observe')draw(s);if(f==='bomb'&&enemy[0])hurt(enemy[0],1,z,opponent(s));if(f==='chief')enemy.forEach(x=>hurt(x,1,z,opponent(s)));if(f==='seal'&&enemy[0])enemy[0].sealed=true;if(f==='moveEnemy'&&enemy[0])moveUnit(opponent(s),z,enemy[0],(z+1)%3);if(f==='bridge')S[s].res=Math.min(5,S[s].res+2);if(f==='medic'){let w=worst(s);if(w)heal(w.u,2)}if(f==='weaver'){S[s].res=Math.min(5,S[s].res+1);let move=allUnits(s)[0];let to=[0,1,2].find(x=>x!==z&&S.zones[x][s].length<2);if(move&&to!==undefined)moveUnit(s,move.z,move.u,to)}if(S.zones[z].field?.owner===s&&S.zones[z].field.card.fx==='trellis'){S[s].res=Math.min(5,S[s].res+1);u.d+=1}clean();render()}
function resolveFx(s,c,target){const os=opponent(s),ours=allUnits(s),fx=c.fx;if(typeof target==='number'&&S.zones[target].field?.card.fx==='sealedRoom'&&S.zones[target].field.owner!==s)return;if(fx==='ledger'||fx==='harvest'||fx==='table')S[s].res=Math.min(5,S[s].res+(fx==='ledger'?2:2));if(fx==='harvest'||fx==='table')S[os].res=Math.min(5,S[os].res+1);if(fx==='ledger'&&S.zones.some(z=>control(z).owner===s))draw(s);if(fx==='healAll')ours.forEach(x=>heal(x.u,1));if(fx==='ritual'){S[s].res=Math.max(0,S[s].res-1);S[s].fame+=2}if(fx==='gamble'&&target?.u){target.u.temp=(target.u.temp||0)+2;hurt(target.u,1,target.z,s)}if(fx==='ready'&&target?.u)target.u.used=false;if(fx==='sacrifice'&&target?.u){S.zones[target.z][s].splice(target.ui,1);S[s].res=Math.min(5,S[s].res+3);draw(s)}if(fx==='ticket'&&target?.u){heal(target.u,2);S[s].supported=true};if(fx==='convert'){if(S[s].res>0){S[s].res--;S[s].fame++}}if(fx==='handshake')S[s].shield++;if(fx==='archive'&&typeof target==='number'){S.zones[target][s].forEach(u=>heal(u,2));if(control(S.zones[target]).owner===s)S[s].fame++}if(fx==='ironRain'&&typeof target==='number'){for(const x of S.zones[target][os])hurt(x,2,target,os);for(const x of S.zones[target][s])hurt(x,1,target,s)}if(fx==='scatter'&&typeof target==='number'){[...S.zones[target].p,...S.zones[target].b].forEach(u=>moveUnit(u===S.zones[target].p.find(x=>x===u)?'p':'b',target,u,(target+1)%3))}if(fx==='chair'&&typeof target==='number')S.zones[target].chair=true;if(fx==='alarm'){let w=worst(s);if(w)hurt(w,1,w.z,s);let e=worst(os);if(e)hurt(e,1,e.z,os)}if(fx==='roots'){let x=S[s].discard.find(x=>x.t==='角色'&&x.c<=1);if(x){S[s].discard.splice(S[s].discard.indexOf(x),1);S[s].hand.push(x)}}if(fx==='fifth'){if(S[s].res>=2){S[s].res-=2;S[s].fame+=2}else S[s].res=Math.min(5,S[s].res+3)}if(fx==='echo'){let low=S.p.fame<=S.b.fame?'p':'b';if(s===low){let w=worst(s);if(w)heal(w.u,2)}}if(fx==='letter'){draw(s,2);if(S[s].hand.length>7)discard(s,S[s].hand.pop())}if(fx==='eclipse')S.eclipse=S.p.fame<=S.b.fame?'p':'b';if(fx==='rain'){let f=S.zones.find(z=>z.field?.owner===s);if(f)f.field=null,S[s].fame+=2;else S[s].res=Math.min(5,S[s].res+2)}if(fx==='dream'){let x=S[s].discard.find(x=>x.c<=2);if(x){S[s].discard.splice(S[s].discard.indexOf(x),1);S[s].hand.push(x)}}if(fx==='rumor'){for(const who of ['p','b']){let high=S[who].hand.slice().sort((a,b)=>b.c-a.c)[0];if(high)discard(who,S[who].hand.splice(S[who].hand.indexOf(high),1)[0])}}if(fx==='tax'){S.tax=true;S.taxFor=os}if(fx==='counter'){S.counter=true;S.counterFor=os}if(fx==='counterEvent'){S.counterEvent=true;S.counterEventFor=os}if(fx==='swap'){let units=allUnits(s);if(units.length>1){let from=units[0].z,to=(from+1)%3;if(S.zones[to][s].length<2)moveUnit(s,from,units[0].u,to)}}clean()}
function allUnits(s){return S.zones.flatMap((z,zi)=>z[s].map((u,ui)=>({u,z:zi,ui})))}
function worst(s){return allUnits(s).sort((a,b)=>(b.u.damage/defense(b.u,S.zones[b.z],s))-(a.u.damage/defense(a.u,S.zones[a.z],s)))[0]}
function heal(u,n){if(u)u.damage=Math.max(0,u.damage-n)}
function hurt(u,n,z,s){if(S[s].shield){S[s].shield--;note(`${side(s)}以承諾抵銷傷害。`);return}u.damage+=n}
function moveUnit(s,from,u,to){if(!S.zones[to]||S.zones[to][s].length>=2)return;let a=S.zones[from][s],i=a.indexOf(u);if(i>=0){a.splice(i,1);S.zones[to][s].push(u)}}
function clean(){S.zones.forEach((z,zi)=>['p','b'].forEach(s=>z[s]=z[s].filter(u=>{if(u.damage>=defense(u,z,s)){note(`「${u.card.n}」退場。`);if(u.card.fx==='rush')S[s].res=Math.min(5,S[s].res+1);return false}return true})))}
function battle(z,pi,bi){let zone=S.zones[z],p=zone.p[pi],b=zone.b[bi];if(!p||!b||p.used||p.sealed)return;hurt(p,power(b,zone,'b'),z,'p');hurt(b,power(p,zone,'p')+(p.card.fx==='singer'?1:0),z,'b');p.used=true;if(zone.field?.owner==='p'&&zone.field.card.fx==='ropeField')hurt(p,1,z,'p');if(zone.field?.owner==='b'&&zone.field.card.fx==='ropeField')hurt(b,1,z,'b');note(`「${p.card.n}」與「${b.card.n}」在<strong>${zone.n}</strong>交鋒。`);clean();S.selected=null;render()}
function score(s){let n=0;S.zones.forEach(z=>{if(control(z).owner===s){n++;if(s==='p')n+=z.p.filter(u=>u.card.fx==='gardener').length;if(z.chair)n+=2}});if(s==='p'&&n>=2&&allUnits('p').some(x=>x.u.card.fx==='elder'))n++;if(S[s].supported&&allUnits(s).some(x=>x.u.card.fx==='arbiter'))n++;S[s].fame+=n;if(n)note(`${side(s)}結算控制，獲得 ${n} 聲望。`);return n}
function end(){if(S.turn!=='p'||S.ended)return;score('p');if(checkEnd())return;S.turn='b';S.selected=null;render();setTimeout(botTurn,450)}
function botTurn(){if(S.ended)return;start('b');let b=S.b,c=b.hand.find(x=>x.t==='角色'&&cost(x,'b')<=b.res),field=b.hand.find(x=>x.t==='場域'&&cost(x,'b')<=b.res),other=b.hand.find(x=>x.t==='行動'&&cost(x,'b')<=b.res);if(c){let zs=S.zones.map((z,i)=>({i,v:control(z).p-control(z).b})).filter(x=>S.zones[x.i].b.length<2).sort((a,b)=>b.v-a.v);if(zs.length)playZone('b',c,b.hand.indexOf(c),zs[0].i)}if(field){let zi=S.zones.map((z,i)=>({i,v:control(z).p-control(z).b})).sort((a,b)=>b.v-a.v)[0].i;playZone('b',field,b.hand.indexOf(field),zi)}if(other&&!(S.counter&&S.counterFor==='b'))resolve('b',other,b.hand.indexOf(other));if(S.counter&&S.counterFor==='b')S.counter=false;S.zones.forEach((z,zi)=>{let u=z.b.find(x=>!x.used&&!x.sealed),target=z.p[0];if(u&&target){target.damage+=power(u,z,'b');u.damage+=power(target,z,'p');u.used=true;note(`電腦的「${u.card.n}」發起交鋒。`);clean()}});score('b');if(checkEnd())return;S.round++;S.eclipse=null;start('p');render()}
function start(s){S[s].res=3;S[s].action=false;S[s].event=false;S.supported[s]=false;S.zones.forEach(z=>z[s].forEach(u=>{u.used=false;u.sealed=false;u.temp=0}));draw(s);if(S.zones.some(z=>z.field?.owner===s&&z.field?.card.fx==='archiveField'))draw(s);if(allUnits(s).some(x=>x.u.card.fx==='calibrate'))draw(s);S.turn=s}
function checkEnd(){if(S.p.fame>=12||S.b.fame>=12||S.timeline>=10){S.ended=true;let winner=S.p.fame===S.b.fame?'平手':S.p.fame>S.b.fame?'你':'電腦';note(`<strong>${winner==='平手'?'議約以平手結束。':winner+' 贏得議約！'}</strong>`);render();return true}return false}
function modal(html){root.innerHTML=`<div class="modal-back" data-close><section class="modal" role="dialog" aria-modal="true"><button class="btn close" data-close>關閉</button>${html}</section></div>`}
function guide(step=0){const slides=[['歡迎來到曙痕','天空裂痕正在閉合。你要在三座領域部署角色，率先累積 <b>12 聲望</b>。','看見領域上的 <b>你控制</b>，就代表那裡會在回合結束替你得分。'],['一回合只記四件事','<b>曙光：</b>曦質補到 3、抽 1 張。<br><b>策議：</b>打角色、裝備、場域；行動每回合限一張。<br><b>交鋒：</b>點自己的角色，再點同區敵人。<br><b>餘波：</b>比較控制並獲得聲望。','角色攻擊決定交鋒傷害；防禦是它可承受的傷害。'],['第一局從這裡開始','選一個陣營。<b>琥珀庭</b>穩健得分，<b>燼行團</b>攻勢爆發，<b>靛幕局</b>移動干擾，<b>苔盟</b>修復與轉化。','底部手牌現在可以完整滑動檢視；每張牌右下角的 i 可開啟介紹。']];let [h,body,foot]=slides[step];let buttons=step<2?`<button class="btn gold" data-guide="${step+1}">下一步 →</button>`:`<button class="btn gold" data-action="pick">選擇陣營開始</button>`;modal(`<h2>${h}</h2><div class="tutorial-art"></div><p>${body}</p><p>${foot}</p><div class="steps">${slides.map((_,i)=>`<i class="${i===step?'on':''}"></i>`).join('')}</div>${buttons}`)}
function factionPicker(){modal(`<h2>選擇第一副牌</h2><p>每副初始牌組 30 張，會從所選陣營牌與命運牌構成。可隨時重新開局嘗試其他路線。</p><div class="faction-grid">${['amber','ember','indigo','moss'].map(f=>{let x=FACTIONS[f];return `<button class="faction" data-faction="${f}" style="--c:${x.color}"><b>${x.icon} ${x.name}</b><small>${x.motto}</small></button>`}).join('')}</div>`)}
function collection(filter='all'){let list=filter==='all'?CARDS:CARDS.filter(c=>c.f===filter||c.t===filter);modal(`<h2>曙痕圖鑑 · ${list.length} 張</h2><p>每張牌都已登錄費用、類型、效果、稀有度與陣營美術。遊戲內右下角 <b>i</b> 可隨時查看介紹。</p><div class="filters">${[['all','全部'],...Object.entries(FACTIONS).map(([k,v])=>[k,v.name]),...['角色','行動','事件','裝備','場域','命運'].map(x=>[x,x])].map(([k,n])=>`<button class="filter ${filter===k?'on':''}" data-filter="${k}">${n}</button>`).join('')}</div><div class="gallery">${list.map(c=>cardHTML(c,-1,false,true)).join('')}</div>`)}
function handViewer(){modal(`<h2>你的手牌 · 放大檢視</h2><p>選擇一張牌可以查看完整介紹；在桌面上可用滑鼠滾輪橫向瀏覽，在手機上左右滑動。</p><div class="gallery hand-gallery">${S.p.hand.map(c=>cardHTML(c,-1,false,true)).join('')||'<p>手牌已空。</p>'}</div>`)}
function info(id){let c=CARDS.find(x=>x.id===id),f=FACTIONS[c.f],usage=c.t==='角色'?'部署到領域後，以攻擊力爭奪控制。':c.t==='場域'?'選擇最需要翻盤的領域，場域會改變控制比較。':c.t==='命運'?'它是一次性風險選擇，通常在落後時價值最高。':'先確認本回合的資源與目標，再支付費用。';modal(`<h2>${c.n}</h2><p><b style="color:${f.color}">${f.icon} ${f.name}</b>　${c.t}　稀有度 ${c.r}　費用 ${c.c}</p><div class="art" style="height:240px;--art:url('${art(c)}')"><span>${TYPE_ICON[c.t]}</span></div><p><b>效果：</b>${c.e}</p><p><b>使用提示：</b>${usage}</p><p class="card-note">這張牌的設計目的，是讓玩家在「立即收益」與「保留資源」之間做一次可讀的選擇。</p>`)}
document.addEventListener('click',e=>{let close=e.target.closest('[data-close]'),act=e.target.closest('[data-action]'),card=e.target.closest('[data-card]'),unit=e.target.closest('[data-unit]'),zone=e.target.closest('[data-zone]'),inf=e.target.closest('[data-info]'),g=e.target.closest('[data-guide]'),f=e.target.closest('[data-faction]'),flt=e.target.closest('[data-filter]');if(close&&(e.target===close||close.tagName==='BUTTON')){root.innerHTML='';return}if(g){guide(+g.dataset.guide);return}if(f){root.innerHTML='';newGame(f.dataset.faction);return}if(flt){collection(flt.dataset.filter);return}if(inf){info(inf.dataset.info);return}if(act){if(act.dataset.action==='guide')guide();if(act.dataset.action==='collection')collection();if(act.dataset.action==='hand')handViewer();if(act.dataset.action==='new')factionPicker();if(act.dataset.action==='pick')factionPicker();if(act.dataset.action==='end')end();return}if(card&&card.dataset.card!==''){chooseCard(+card.dataset.card);return}if(unit){let [s,z,i]=unit.dataset.unit.split(',');z=+z;i=+i;if(S.turn!=='p'||S.ended)return;if(S.selected?.mode==='own'&&s==='p'){playOwn('p',S.selected.card,S.selected.i,z,i);S.selected=null;render();return}if(s==='p'){let u=S.zones[z].p[i];if(!u.used&&!u.sealed)S.selected={mode:'attack',s:'p',z,i};render();return}if(s==='b'&&S.selected?.mode==='attack'&&S.selected.z===z)battle(z,S.selected.i,i);return}if(zone){let z=+zone.dataset.zone;if(S.turn==='p'&&S.selected?.mode==='zone'){playZone('p',S.selected.card,S.selected.i,z);S.selected=null;render()}return}});
newGame();if(!localStorage.getItem('dawnscar-guide-seen')){localStorage.setItem('dawnscar-guide-seen','1');guide();}
